[tool.commitizen]
name = "cz_customize"
version = "0.1.0"
version_files = [
    "setup.py",
]
bump_message = "bump: version $current_version → $new_version [skip ci]"

[tool.commitizen.customize]
bump_pattern = '^(feat|fix|build|docs)(\(.+\))?(!)?'
bump_map = {"feat" = "MINOR", "fix" = "PATCH", "build" = "PATCH", "docs" = "PATCH"}
