name: pytest
on:
  push:
    branches:
      - main

jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: |
            requirements/base.txt
            requirements/test.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --requirement requirements/test.txt
          python -m pip install --editable .

      - name: pytest
        run: |
          pytest --cov=normalise tests/

      - name: pytest mypy
        run: |
          pytest --mypy normalise

      - uses: commitizen-tools/commitizen-action@0.14.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog: false
          commitizen_version: "2.32.2"
          no_raise: ""
